GET http://localhost:8080/api/v1/employees
Accept: application/json

###

GET http://localhost:8080/api/v1/employees/1
Accept: application/json

###

GET http://localhost:8080/api/v1/employees/3
Accept: application/json

###

PUT http://localhost:8080/api/v1/employees/1
Accept: application/json
Content-Type: application/json

{
  "name": "Peter Müller",
  "role": "Chef Chef"
}

###

PUT http://localhost:8080/api/v1/employees/3
Accept: application/json
Content-Type: application/json

{
  "name": "Petra Klein",
  "role": "Aushilfe"
}

###

POST http://localhost:8080/api/v1/employees
Accept: application/json
Content-Type: application/json

{
  "name": "Luke Skywalker",
  "role": "Jedi Meister"
}

###

DELETE http://localhost:8080/api/v1/employees/2
Accept: application/json

###

DELETE http://localhost:8080/api/v1/employees/5
Accept: application/json